# Ansible create virtual host
#
    - name: apache vhost file
      template:
        src: "templates/vhost_ssl.conf.j2"
        dest: "/etc/apache2/sites-available/{{app_domain}}.conf"
        mode: u=rw,g=r,o=r

# Enable the virtual host
    - name: Enable the virtual host
      shell: "a2ensite {{app_domain}}"
      register: a2ensite
      changed_when: "'already enabled' not in a2ensite.stdout"
      notify:
        - restart apache2
