# Ansible laravel setup

    # Application key
    # - name: Generate application key
    #  command: php artisan key:generate
    #  args:
    #    chdir: '{{installation_path}}'

    # reset database
    - name: php artisan migrate
      command: php artisan migrate
      args:
        chdir: '{{installation_path}}'

    - name: php artisan migrate:reset
      command: php artisan migrate:reset
      args:
        chdir: '{{installation_path}}'

    # setup database
    - name: php artisan migrate --seed
      command: php artisan migrate --seed
      args:
        chdir: '{{installation_path}}'
