# Ansible laravel setup

    # Application key
    - name: Generate application key
      command: /usr/bin/php8.0 artisan key:generate
      args:
        chdir: '{{installation_path}}'

    # reset database
    - name: Migrate database
      command: /usr/bin/php8.0 artisan migrate
      args:
        chdir: '{{installation_path}}'

    - name: Reset database
      command: /usr/bin/php8.0 artisan migrate:reset
      args:
        chdir: '{{installation_path}}'

    # setup database
    - name: setup database
      command: /usr/bin/php8.0 artisan migrate --seed
      args:
        chdir: '{{installation_path}}'
