# Multitenant deployment
#
# edit configuration files, by using environment variables
# configuration.
#
# BASE_URL              for central application
# INSTALLATION_PATH     installation directory

# DB_HOST               database host
# DB_USERNAME           and user name
# DB_PASSWORD
# DB_DATABASE           and name
#
# to execute:
# ansible-playbook deploy.yml
---

- name: Simple local playbook

  gather_facts: true
  hosts: localhost

  vars:
    base_url: "{{lookup('env','BASE_URL')}}" 
    tenant_url: "{{lookup('env','TENANT_URL')}}" 
    installation_path: "{{lookup('env','INSTALLATION_PATH')}}"
    server_path: "{{lookup('env','SERVER_PATH')}}"
    env_file: '{{installation_path}}/.env'
    db_username: "{{lookup('env','DB_USERNAME')}}"
    db_password: "{{lookup('env','DB_PASSWORD')}}"
    db_database: "{{lookup('env','DB_DATABASE')}}"

  roles:
    - env
    - directories
    - laravel

