# Multitenant installation
#
# Full installation of the multitenant application
#
# Pre-requisites: An up and running Apache web server
#
# APP_URL               URL to access the central application
# INSTALLATION_PATH     where the sources are fetched (outside the Apache served directorie)
# PUBLIC_PATH           where the public directory is located (inside the Apache served directories)

# DB_USERNAME           and user name
# DB_PASSWORD
# DB_DATABASE           and name
#
# to execute:
# ansible-playbook --inventory hosts --key-file $TF_VAR_PRIVATE_KEY install.yml
---

- name: Multitenant application installation

  gather_facts: true
  hosts: multi_server
  become: yes
  become_method: sudo
  become_user: root

  vars:
    app_url: "{{lookup('env','APP_URL')}}" 
    tenant_url: "{{lookup('env','TENANT_URL')}}" 
    installation_path: "{{lookup('env','INSTALLATION_PATH')}}"
    public_path: "{{lookup('env','PUBLIC_PATH')}}"
    env_file: '{{installation_path}}/.env'
    db_username: "{{lookup('env','DB_USERNAME')}}"
    db_password: "{{lookup('env','DB_PASSWORD')}}"
    db_database: "{{lookup('env','DB_DATABASE')}}"
    translate_api_key: "{{lookup('env','TRANSLATE_API_KEY')}}"

  roles:
    - git_clone
    - create_db
    #- env
    - directories
    #- laravel

  # tasks:
  #   - name: Display context information
  #     debug: 
  #       msg:
  #         - "APP_URL = {{ app_url }}"
  #         - "INSTALLATION_PATH = {{ installation_path }}"
  #         - "Welcome to the Multitenant Web Application Framework installation"

  tasks:
    - name: test root access
      command: 'grep root /etc/shadow'  
      

