# Ansible create directories

    # Create laravel directories
    - name: Create laravel directories
      file:
        path:  "{{ item }}"
        state: directory
        mode: '0777'
      loop:
        - '{{installation_path}}/storage/framework'
        - '{{installation_path}}/storage/framework/sessions'
        - '{{installation_path}}/storage/framework/views'
        - '{{installation_path}}/storage/framework/cache'
        - '{{installation_path}}/storage/app/backup'
        - '{{installation_path}}/storage/tenanttest'
        - '{{installation_path}}/storage/tenanttest/app'
        - '{{installation_path}}/storage/tenanttest/app/backup'

    # Create result directory
    - name: Create results directory
      file:
        path:  '{{installation_path}}/results'
        state: directory
        mode: '0755'

    # writable directories
    - name: make some directories writable
      file:
        path: "{{installation_path}}/storage"
        state: directory
        mode: 0777
        recurse: no
        
    - name: make some subdirectories writable
      file:
        path: "{{installation_path}}/{{item}}"
        state: directory
        mode: 0777
        recurse: yes
      with_items:
        - app
        - framework

    - name: make some files executable
      file:
        path: "{{ installation_path }}/{{item}}"
        mode: 0744
      with_items:
        - test.sh
        - vendor/laravel/dusk/bin/chromedriver-linux

    # writable files
    - name: Ensure file are executable
      command: chmod +x "{{ installation_path }}/{{item}}"
      with_items:
        - test.sh
        - vendor/laravel/dusk/bin/chromedriver-linux
